### ISSUE TITLE
Fix filenames with bad characters

### ISSUE THREAD

**Issue by cool-RR** [pyvideo/data#1037]
This repo can't be checked out on Windows, because it has two filenames with the characters `"` and `?`:

```
error: invalid path 'fosdem-2017/videos/fosdem-2017-flavien-raynaud-python-data-structures-implementationlist,-dict:-how-does-cpython-actually-implement-them?.json'
error: invalid path 'fosdem-2017/videos/fosdem-2017-jonathan-slenders-python-and-"the-solid-principles".json'
```

These are probably not good characters to have in a filename regardless of operating system.

Any chance these could be renamed so it'll be easier for Windows users to use this repo?

**Comment by logston** [comment]
Sure! Do you mind issuing the PR?
