### ISSUE TITLE
EuroPython 2020

### ISSUE THREAD

**Issue by gilgamezh** [pyvideo/data#1041]
Hello! All Europython 2020 are online on youtube. 

https://ep2020.europython.eu/

https://blog.europython.eu/post/632313693115416577/europython-2020-edited-videos-are-online

Is there any example on how to create the data for this? I saw pyvideo has all previous years. I'm happy to help with it

**Comment by akielbowicz** [comment]
Hi @gilgamezh,

You can use this tool to get the data from Youtube https://github.com/pyvideo/pyvideo_scrape
it's pretty easy to setup but it gets the raw data and it might need some polishing (which is optional).

Here you have a guide on [CONTRIBUITING](https://github.com/pyvideo/data/blob/master/CONTRIBUTING.rst) where you  can found more information in the format and schemas.

Glad you're contribuiting :)

**Comment by gilgamezh** [comment]
@akielbowicz PR open! :-)
