### ISSUE TITLE
PyCon Italia 2022

### ISSUE THREAD

**Issue by yednapg** [pyvideo/data#1109]
1. Is this repository active? if a maintainer is needed I love to be the maintainer of this repository
2. Is anyone working on it, if not so I am going to start working on adding PyCon Italia 2022 videos?

**Comment by logston** [comment]
Hey @yednapg, this repo is still active and I'd be very grateful if you took on this issue.

**Comment by yednapg** [comment]
Hey, @logston Thank You for that, I'll start working on it.

**Comment by jonafato** [comment]
Resolved by #1133
