### ISSUE TITLE
PyCon US 2023

### ISSUE THREAD

**Issue by treyhunner** [pyvideo/data#1127]
- Schedule: https://us.pycon.org/2023/schedule/
- Playlist: https://www.youtube.com/playlist?list=PL2Uw4_HvXqvY2zhJ9AMUa_Z6dtMGF3gtb

I also noticed that PyCon US 2022 was missing, so I opened #1126 for that and noted the steps that I think would be necessary for getting this data from YouTube.

**Comment by ewdurbin** [comment]
`https://us.pycon.org/2023/schedule/conference.json` might be helpful :)
