### ISSUE TITLE
References to CONTRIBUTORS.rst outdated

### ISSUE THREAD

**Issue by joshmorel** [pyvideo/data#113]
Hi, I'm looking to contribute to the data repo but got stuck on the fact that references to CONTRIBUTORS.rst in both the [README](https://github.com/pyvideo/data/blob/master/README.rst) & [CONTRIBUTING](https://github.com/pyvideo/data/blob/master/CONTRIBUTING.rst) docs are outdated.

In my first PR I was going to simply remove the references. Before going ahead, I wanted to log the issue and see if there are is any desire to elaborate on the contributors list in any other part of the docs beyond what is in [CONTRIBUTORS_WITHOUT_COMMITS](https://github.com/pyvideo/data/blob/master/CONTRIBUTORS_WITHOUT_COMMITS.rst).

If there's no concern, I'll go ahead with the PR this Tues, Nov 15.

**Comment by logston** [comment]
Hi @joshmorel, thanks for catching this! Can you update the docs so they says something like?:

```
Find our contributors here: <github link to contirbutors> and here: <link to CONTRIBS_WITHOUT_COMMITS>
```

**Comment by joshmorel** [comment]
Sure thing - assign me I'll put in my PR tonight.

**Comment by Daniel-at-github** [comment]
Done in #115
