### ISSUE TITLE
EuroScipy 2016 

### ISSUE THREAD

**Issue by logston** [pyvideo/data#12]
https://github.com/pytube/data/issues/112

**Comment by Daniel-at-github** [comment]
EuroSciPy 2016 will take place in Erlangen (Germany) from the 23 to the 27 of August 2016.
Web: https://www.euroscipy.org/2016/
Playlist for 2015 and 2014: https://www.youtube.com/user/EnthoughtMedia/playlists

**Comment by Daniel-at-github** [comment]
I have sent an email to euroscipy-org (at) python (dot) org asking for info on this.

**Comment by redapple** [comment]
Looks like the 2016 videos were never published.

**Comment by Daniel-at-github** [comment]
Seems safe to close the issue
