### ISSUE TITLE
PyOhio 2016

### ISSUE THREAD

**Issue by logston** [pyvideo/data#14]
https://github.com/pytube/data/issues/142

**Comment by logston** [comment]
@mattboehm Has a branch for with work here: https://github.com/mattboehm/data/tree/pyohio-2016/

**Comment by mattboehm** [comment]
Created a PR at https://github.com/pyvideo/data/pull/95

**Comment by mattboehm** [comment]
The PR was closed so we should be able to close this.

@logston I noticed that the pyohio 2016 videos disable embeds, which make the pyvideo page less useful. Do you know if there's anyone to talk to about changing this? Past years' videos appear to allow embeds.

**Comment by codersquid** [comment]
Talk to @CarlFK

**Comment by mattboehm** [comment]
@CarlFK any chance you can help with making the PyOhio 2016 movies embeddable?

**Comment by logston** [comment]
I think the links just need to be converted. They are currently:

```http://youtu.be/<video_id>```

They should be of the form ```http://www.youtube.com/watch?v=<video_id>```


They youtube tool should help with this:
https://github.com/pyvideo/data/blob/master/tools/youtube.py

```
python tools/youtube.py -p pyohio-2016
```

**Comment by redapple** [comment]
I believe this one can be closed:
- http://pyvideo.org/events/pyohio-2016.html
- #95 + #114

**Comment by logston** [comment]
Nice.
