### ISSUE TITLE
PyCon India

### ISSUE THREAD

**Issue by logston** [pyvideo/data#15]
https://github.com/pytube/data/issues/144

**Comment by Daniel-at-github** [comment]
Pycon india playlists (2012, 2013, 2014, 2015): https://www.youtube.com/user/inpycon/playlists

**Comment by Daniel-at-github** [comment]
* [ ] PyCon India 2012 #516
* [ ] PyCon India 2013
* [ ] PyCon India 2014
* [x] PyCon India 2015 #253 http://pyvideo.org/events/pycon-india-2015.html
* [x] PyCon India 2016 #168 http://pyvideo.org/events/pycon-india-2016.html
* [ ] PyCon India 2017
* [ ] PyCon India 2018

**Comment by Daniel-at-github** [comment]
This issue have been split into years.
I will close it as duplicate.
