### ISSUE TITLE
Pycon Ireland 2016

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#157]
~~~ yaml
- title: Pycon Ireland 2016
  dir: pycon-ireland-2016
  youtube_list: https://www.youtube.com/playlist?list=PLNeBS51Q0m98rI6kyTd5_-33ckRgjUEG3
  issue: 157
  language: eng
~~~

**Comment by redapple** [comment]
@Daniel-at-github , https://github.com/pyvideo/data/pull/128 was merged recently.
Is something missing from the conference?

**Comment by redapple** [comment]
2 talks from the playlist are not in pycon-ie-2016/:

* https://www.youtube.com/watch?v=CT6Mn8UZqnY : Lightning talks, missing indeed
* https://www.youtube.com/watch?v=PWRlp0LupbQ : looks like a duplicate of https://www.youtube.com/watch?v=pWtr8OTeOc8

**Comment by Daniel-at-github** [comment]
Oops! It's a duplicate. My bad.

**Comment by redapple** [comment]
I added the missing talk in https://github.com/pyvideo/data/pull/158
