### ISSUE TITLE
PyCon Argentina 2016

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#162]
~~~ yaml
- title: PyCon Argentina 2016
  dir: pycon-ar-2016
  youtube_list: https://www.youtube.com/channel/UCvRnpXXhZuMU4zfVL62DYZw
  issue: 162
  language: spa
~~~

**Comment by Daniel-at-github** [comment]
http://ar.pycon.org/schedule/

Upload not finished, missing:
* Modelo de Optimización de Despliegue de Redes móviles con Python y Spark
*  Introducción a programación paralela con PyOpenCL
* ...

**Comment by redapple** [comment]
I believe this can be closed.
