### ISSUE TITLE
PyCon Zim 2016

### ISSUE THREAD

**Issue by redapple** [pyvideo/data#167]
* Schedule: http://zw.pycon.org/pages/talks.html
* YouTube playlist: https://www.youtube.com/playlist?list=PL0DWrZc14m8vt-jaJD35mPqpYDXvyoHiC

**Comment by redapple** [comment]
@orangefriday , are you still working on this? any updates? Thanks.

**Comment by orangefriday** [comment]
No, I haven't touch it since May.  I've rebuilt my environment a couple of times and I am still receiving errors after adding this and trying the build again.  I would be curious if someone else has the same issues.

**Comment by thejessleigh** [comment]
I'm was able to pick this one up. Sorry you're having trouble @orangefriday

**Comment by thejessleigh** [comment]
I think this is closed as of #306

**Comment by Daniel-at-github** [comment]
Indeed it is :white_check_mark:
http://pyvideo.org/events/pycon-zim.html
