### ISSUE TITLE
PyDay Rafaela 2016

### ISSUE THREAD

**Issue by redapple** [pyvideo/data#170]
* Schedule: http://rafaela2016.pyday.com.ar/#cronograma
* YouTube playlist: https://www.youtube.com/playlist?list=PLqqrNNI-kvR0DQ9o3S81UptYML2hZ8W2j

**Comment by thejessleigh** [comment]
Note: the link for the schedule does not work and content is not available on archive.org for it.

**Comment by redapple** [comment]
See https://github.com/pyvideo/data/pull/263
Thank you @thejessleigh 
Closing
