### ISSUE TITLE
Write the Docs 2015

### ISSUE THREAD

**Issue by redapple** [pyvideo/data#171]
I'm not sure it's directly Python-related but this repo already has 2013, 2014 and 2016 editions.

* Schedule: http://www.writethedocs.org/conf/na/2015/schedule/
* Playlist: https://www.youtube.com/playlist?list=PLmV2D6sIiX3UW1kPWlhzyo4lr6e3US6re

**Comment by thejessleigh** [comment]
I'm at the PyCon sprints right now. I'll take this one.

**Comment by redapple** [comment]
See https://github.com/pyvideo/data/pull/262
Thank you @thejessleigh !
Closing.
