### ISSUE TITLE
FOSDEM 2017 Python devroom

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#192]
~~~ yaml
schedule : https://fosdem.org/2017/schedule/track/python/
videos:
    # Only python* files
    - http://mirror.as35701.net/video.fosdem.org/2017/H.1308/
    - http://mirror.onet.pl/pub/mirrors/video.fosdem.org/2017/UD2.120/
~~~

**Comment by lorenanicole** [comment]
@logston these videos aren't hosted on YouTube, does that exclude it from being included on PyVideo?

**Comment by lorenanicole** [comment]
@Daniel-at-github are there thumbnail img urls? Looks like that's a mandatory field for a PR.

**Comment by Daniel-at-github** [comment]
I'm afraid that we are out of luck in this, but you could do as https://github.com/pyvideo/data/blob/master/scipy-2012/videos/forking-your-way-to-success-and-happiness-how-gi.json and add 
~~~ json
 "thumbnail_url": null,
~~~

If you feel brave enough you could try [tubeup](https://github.com/bibanon/tubeup) to upload the videos to archive.org (not sure if it will work with non-youtube videos), there thumbnails are for free :innocent: 

We have a [collection](https://archive.org/details/pyvideo) in archive.org

**Comment by lorenanicole** [comment]
BTW I wrote a little script to pull out the information from FOSSDEM, not sure if the website greatly changes year to year ... but @logston if you want it I have it!

**Comment by lorenanicole** [comment]
@Daniel-at-github if it isn't a big pain in the butt I'll do that :-) max value for our PyVideo lovers!!!

**Comment by redapple** [comment]
This can be closed. See #282
