### ISSUE TITLE
Needs slides of the video 

### ISSUE THREAD

**Issue by jack17529** [pyvideo/data#199]
Here is the video- https://www.youtube.com/watch?v=wyJZBwY6EEo
 , I think the slides are really cool and should be uploaded here.

**Comment by redapple** [comment]
@jack17529 , are you suggesting that a link to the [ipython noteboook for the talk](https://github.com/adamhaney/python-ast-talk/blob/master/AST%20talk.ipynb) is linked to the metadata of the video?

**Comment by jack17529** [comment]
@redapple  great thanx!!
