### ISSUE TITLE
Bay Piggies

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#201]
~~~ yml
- title: Bay Piggies
  dir: bay-piggies
  youtube_list: https://www.youtube.com/channel/UCBJV1sd5XcVhijm13pWfBCg/videos
  language: eng
~~~

**Comment by thejessleigh** [comment]
There are several years worth of videos on this YouTube channel. Should they be separated out by year? Or do they belong all in one directory together?

**Comment by thejessleigh** [comment]
Also, it looks like this youtube channel is relatively active. Do we have any protocols on keeping up with active YouTube uploads from meetup accounts?

**Comment by Daniel-at-github** [comment]
What I have seen in pyvideo is mostly annual conferences. Those are easy to split by year.
I think that Bay Piggies videos belong all in one directory together. And I don't know of any protocols on keeping up with active YouTube uploads from meetup accounts.
