### ISSUE TITLE
 Django cong

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#204]
~~~ yml
- title: Django cong
  dir: djangocong
  youtube_list: https://www.youtube.com/channel/UCz3p12B1GXiPi7FkS7JejUw
  language: fra
~~~

**Comment by thejessleigh** [comment]
Schedule: http://rencontres.django-fr.org/2012/conferences.html

**Comment by thejessleigh** [comment]
Lightning talks - separate playlist. https://www.youtube.com/playlist?list=PL66702ED0B508F4AB

**Comment by thejessleigh** [comment]
I believe this issue is closed as of this commit https://github.com/thejessleigh/data/commit/b57b673a57b3d9a28037e39f4a814bbfea5217a0

**Comment by Daniel-at-github** [comment]
Done in  #267

@thejessleigh thanks for pointing it out.
