### ISSUE TITLE
Duplicate videos in europython-2011

### ISSUE THREAD

**Issue by smilin-desperado** [pyvideo/data#216]
It looks like some of the videos from the europython 2011 event are duplicated such as

http://pyvideo.org/europython-2011/5-years-of-bad-ideas.html
http://pyvideo.org/europython-2011/5-years-of-bad-ideas-0.html
and the corresponding data files
https://github.com/pyvideo/data/blob/master/europython-2011/videos/5-years-of-bad-ideas-0.json
https://github.com/pyvideo/data/blob/master/europython-2011/videos/5-years-of-bad-ideas.json

In all cases, it looks like most of the metadata is identical with the exception of the video urls (and thumbnail urls). Looks like there are ~50 videos that have duplicates

My suggestion would be to merge the data files and use the most recently uploaded video as the video url. If that sounds reasonable to people, I'll go ahead make the changes and open a PR 😄

**Comment by Daniel-at-github** [comment]
Thanks for the issue @smilin-desperado and your PR offer, I will put you as assignee of the issue.

What I have done when I found something like this, is merge the data files and use all the videos.
Example:
* Delete http://pyvideo.org/europython-2011/5-years-of-bad-ideas-0.html
* Edit video section in http://pyvideo.org/europython-2011/5-years-of-bad-ideas.html like this:
~~~ json
  "videos": [
    {
      "length": 0,
      "type": "youtube",
      "url": "http://www.youtube.com/watch?v=8e0l_Dt28MQ"
    },
    {
      "length": 0,
      "type": "youtube",
      "url": "http://www.youtube.com/watch?v=bpjHa0G9X5w"
    }
  ]
~~~
If you put the most recent first, the second will be a backup option for the user.
