### ISSUE TITLE
Normalize & standardize tags

### ISSUE THREAD

**Issue by kojoidrissa** [pyvideo/data#261]
There's currently a lot of confusion with tags. As an example we have 4 variants for "lightning talk".

- http://pyvideo.org/tag/lightning-talk/
- http://pyvideo.org/tag/lightning-talks/
- http://pyvideo.org/tag/lightningtalk/
- http://pyvideo.org/tag/lightningtalks/

I propose tags be: 
-  space-separated strings
-  all lowercase, for consistency

I'm also going to go through and clean up the multiple variant situations I find. Anyone else is free to help. :-)

**Comment by treyhunner** [comment]
@kojoidrissa I was just about to open an issue about this same thing. I was about to make a YouTube playlist of all PyCon lightning talks and then realized PyVideo might have already solved this problem for me... then I saw the duplicate tag situation for lightning talks.

:+1: for space-separated lowercase strings

I wonder whether things like `WebTest` or `StringIO` should be exceptions. Exceptional cases seem like they'd be rare, so maybe we could just deal with `stringio` and similar looking odd.

Did you clean up the lightning talk ones already?

**Comment by kojoidrissa** [comment]
@treyhunner No, I haven't cleaned them up yet. My fixes there were in a branch that got killed when I was confused about git submodules. I'll get to it in the next day or two.

I considered the 'exceptions' situation, but I felt like it would add to confusion for volunteers wanting to add or update tags. And we've already got MORE than enough confusion as it is. :-)

Perhaps in the future, when things are in more order with the tags, we can go back and consider those types of updates. However, that DOES raise a question of how the search function works on PyVideo: is it case sensitive or not? I don't know.

**Comment by jtemporal** [comment]
> I wonder whether things like `WebTest` or `StringIO` should be exceptions. Exceptional cases seem like they'd be rare, so maybe we could just deal with `stringio` and similar looking odd.

Don't want to sound rude but I'd like to quote the Zen of Python on this matter: _Special cases aren't special enough to break the rules._

> However, that DOES raise a question of how the search function works on PyVideo: is it case sensitive or not? I don't know.

I think the search is made on a "likeness" basis which makes it case insensitive, for instance if you search for `angular` it will find all the videos, including the ones with the tags `Angular` and `angularjs` and also the ones which include `Angular` on the title. Pretty neat =)
