### ISSUE TITLE
Python Brasil 12 (2016)

### ISSUE THREAD

**Issue by redapple** [pyvideo/data#270]
http://2016.pythonbrasil.org.br/
"12ª conferência brasileira da comunidade Python"

* YouTube playlist: https://www.youtube.com/playlist?list=PLDC3uVLxaEQ2QPRucgMwiK22QSgq0aIEJ
* schedule: http://2016.pythonbrasil.org.br/#schedule

**Comment by Daniel-at-github** [comment]
Seems that more videos are coming the next few weeks (#272)
