### ISSUE TITLE
Python Brasil 8 (2012)

### ISSUE THREAD

**Issue by redapple** [pyvideo/data#271]
http://2012.pythonbrasil.org.br/

* schedule: http://2012.pythonbrasil.org.br/en/schedule/index.html
* YouTube playlist: https://www.youtube.com/playlist?list=PLDC3uVLxaEQ3mdpYi_RppFwF4030sTprr

**Comment by redapple** [comment]
@emsecrist , are you still working on it?

**Comment by emsecrist** [comment]
Hi Paul,
I have started working on it but finding the time to continue is a
challenge. If there is someone else who wants to work on it, feel free to
reassign/unassign it.

Thanks,
Eric

**Comment by redapple** [comment]
Thanks for the heads up @emsecrist .
I submitted a PR at #298 .
