### ISSUE TITLE
Move rackspace videos to archive.org 

### ISSUE THREAD

**Issue by logston** [pyvideo/data#3]
https://github.com/pytube/data/issues/23

**Comment by logston** [comment]
@Daniel-at-github @codersquid How's this coming along? Do you need or want help? I can recruit some more people if so.

**Comment by Daniel-at-github** [comment]
Work route:

1. [x] Hack a script to upload a rackspace video to archive.org
2. [ ] Uploading videos to https://archive.org/details/@pytube 
3. [ ] Replacing liks in json files
4. [ ] Update archive.org metadata with pyvideo info.

I'm on step two (look for September 2016 videos). I suppose that it will take several days (and a weekend pause) to finish the upload.

**Comment by logston** [comment]
We are moving all videos to https://archive.org/details/pyvideo I believe.

**Comment by Daniel-at-github** [comment]
Yes, I copied them to the pyvideo collection [ https://archive.org/details/pyvideo ] through the pytube user [ https://archive.org/details/@pytube ]
Uploaded with https://archive.org/details/pyvideo_<pyvideo_id>___<filename?>
Now I have to replace the links in the json files. What is the preferred format for archive.org URLs?

**Comment by logston** [comment]
Great!
Since we will not always know what the best download link is nor do we want to make that decision for consumers of this data, let's go with:

`https://archive.org/details/<item_name>` 

For example:
`https://archive.org/details/europython_2014_event_82`

**Comment by brandon-rhodes** [comment]
I noticed that several video links in my talks were broken, and they all have `rackcdn.com` somewhere in the URL. Am I guessing correctly that they are related to this issue? I was going to offer a pull request to delete the bad links from my own talks, at least, before I did a quick grep and saw that maybe as many as 1,031 links are affected, so I searched and found this issue.

Is there a way forward to getting the links fixed? If not I'll be happy to at least offer a pull request to get the broken links removed from my talks — or a PR to remove all of them if that would be even more helpful.

I'd also be happy to help update them if the videos were indeed safely moved before disappearing!

**Comment by logston** [comment]
Hey @brandon-rhodes, thanks for the offer. Someone recently looked through all of these links and found that only a few were not backed up to archive.org. Those few were subsequently backed up. So, a PR removing the dead links would be awesome! Thank you.
