### ISSUE TITLE
The site has a video of an empty chair, with little to no sound for 30 minutes

### ISSUE THREAD

**Issue by tritium21** [pyvideo/data#300]
It's an empty chair, with inaudible talking amongst conference goers.  There is no content in this video.  What is the procedure to remove this video?

http://pyvideo.org/pygotham-2016/creating-a-bittorrent-client-using-asyncio.html

**Comment by redapple** [comment]
Ha, good catch! just send a PR removing the corresponding JSON file

**Comment by redapple** [comment]
This can be closed ( @Daniel-at-github , @lgh2 )
