### ISSUE TITLE
PyOhio 2017

### ISSUE THREAD

**Issue by thejessleigh** [pyvideo/data#333]

**Comment by thejessleigh** [comment]
https://www.youtube.com/playlist?list=PL2k6bbM_wgjtIH-DmrBuj8QiB8DkDUeqb

**Comment by codersquid** [comment]
I know Carl is waiting on some reviewers to flip the approve switch to make some of the videos public. Once he does that, someone can scrape youtube, or better would be to see if you can use the experimental api he wrote to generate pyvideo json files.

**Comment by tylerdave** [comment]
I used the API @codersquid mentioned and generated the JSON files in #359

**Comment by Daniel-at-github** [comment]
Fixed in #359
