### ISSUE TITLE
PyCon Ar 2012

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#35]
PyCon Ar 2012

|  |  |
| --- | --- |
| **Playlist** | https://www.youtube.com/watch?v=05HfBi2skiw&list=PLkuS0waF8krjwcRHzSJMq_nA67mCFi24T |
|  |  |

**Comment by brettcannon** [comment]
Specifically the following playlists:
- https://www.youtube.com/playlist?list=PLkuS0waF8kril9T9qQUAW6NCptNLZXmHc
- https://www.youtube.com/playlist?list=PLkuS0waF8krjwcRHzSJMq_nA67mCFi24T
- https://www.youtube.com/playlist?list=PLkuS0waF8krgk1ULTg6sGrEBMs46AfoMt

**Comment by Daniel-at-github** [comment]
Now tracking in #575
