### ISSUE TITLE
PyParis 2017

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#393]
June 12-13, 2017

~~~ yaml
 - title: PyParis 2017
   dir: pyparis-2017
   youtube_list: https://www.youtube.com/playlist?list=PLzjFI0G5nSsrzzM6UYs61A01-sVAt3PXC
   language: eng
   related_urls:
   - label: event schedule
     url: http://pyparis.org/schedule.html
   - label: event slides
     url: http://pyparis.org/slides.html
~~~

**Comment by redapple** [comment]
PyParis 2017 videos were added in #342 but 3 videos on the YouTube playlist are missing indeed:
- https://www.youtube.com/watch?v=HiBhYTcmS0w
- https://www.youtube.com/watch?v=iH6JRfP1q78
- https://www.youtube.com/watch?v=CgzJqrBgYLg

(There's also a deleted video in the playlist -- https://www.youtube.com/watch?v=lpw0q5Lgcqo)
