### ISSUE TITLE
PyData NYC 2015

### ISSUE THREAD

**Issue by redapple** [pyvideo/data#402]
* playlist: https://www.youtube.com/playlist?list=PLGVZCDnMOq0ourWlul1F7aYE30VQPaMRL
* schedule: https://pydata.org/nyc2015/schedule/index.html

**Comment by redapple** [comment]
Other playlists (I haven't checked if they contain the same as PyData's):
- https://www.youtube.com/playlist?list=PLGB9meziqbzp8SDNH2_HkrG_uencFUfTD
- https://www.youtube.com/playlist?list=PLY1PWBYflvTGfRPdG65tvN8dko2WyRCXa

**Comment by Daniel-at-github** [comment]
~~~ yaml
- title: PyData New York City 2015
  dir: pydata-new-york-city-2015
  youtube_list:
    - https://www.youtube.com/playlist?list=PLGVZCDnMOq0ourWlul1F7aYE30VQPaMRL
  related_urls:
  - label: Conference schedule
    url: https://pydata.org/nyc2015/schedule/
  language: eng
  dates:
    begin: 2015-11-09
    end: 2015-11-11
    default: 2015-11-09
  issue: 402
  minimal_download: true
  tags:
~~~

**Comment by Daniel-at-github** [comment]
Now tracked in #577
