### ISSUE TITLE
PyCon APAC 2013

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#42]
PyCon APAC 2013

|  |  |
| --- | --- |
| **Web** | http://apac-2013.pycon.jp/ |
| **Playlist** | https://www.youtube.com/watch?v=njj9waa-jJg&list=PLMkWB0UjwFGlNdEZ6c0n13CUsaAti_GEI |
|  |  |

**Comment by logston** [comment]
https://github.com/pyvideo/data/pull/57
