### ISSUE TITLE
PyData Copenhagen

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#457]
Site | URL
------------ | -------------
Youtube channel | https://www.youtube.com/channel/UCphaUFghyyhpd9Fi2nBKsNA/videos
Meetup | https://www.meetup.com/es-ES/PyData-Copenhagen/

**Comment by thejessleigh** [comment]
This youtube channel only has three videos in it, each of which is under 2 minutes. It looks like they haven't had any activity in months. Do we know anyone at that meetup who has information about whether or not they'll be uploading any content?

**Comment by Daniel-at-github** [comment]
@andersbogsnes, sorry to bother (spam) you. 

Do you know if PyData Copenhagen is producing video content (in order to index it in Pyvideo)? If so, please, contact with us in this github issue (meanwhile we will assume no content and close the issue).

Thanks in advance.
