### ISSUE TITLE
PyCon Uruguay 2013

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#46]
PyCon UY 2013

|  |  |
| --- | --- |
| **Playlist** | https://www.youtube.com/watch?v=GzorUnKdwb4&list=PLfvJ0GULhS69Ir4As8Vd5wrqRbOZKgIX8 |
|  |  |

**Comment by redapple** [comment]
Schedule can be found at https://web.archive.org/web/20131103102200/http://uy.pycon.org/es/schedule
