### ISSUE TITLE
Remove video A Simplificação Textual como instrumento de Inclusão Cognitiva

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#500]
In https://github.com/pyvideo/pyvideo/issues/153 @vwoloszyn asks:

> I would like to remove my video from pyvideo.org. I am  asking this issue here because the website does not provide any way to  do that. http://pyvideo.org/speaker/vinicius-woloszyn.html Thank you very much in advance.

**Comment by vwoloszyn** [comment]
a full link to that http://pyvideo.org/scipyla-2016/a-simplificacao-textual-como-instrumento-de-inclusao-cognitiva.html
