### ISSUE TITLE
Proposal: Perform initial minimal downloads for the conferences in the backlog

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#517]
The amount of issues in the backlog is not solvable with the actual contributors, my proposal is to perform an initial minimal download of scraped data. This enables:
* Give presence to the backlog.
* A first "fast" response to new conferences.
* An skeleton entry to casual users to add URLs to slides, etc
* Know what is missing (If description and speakers is blank, then is pending).

**Comment by Daniel-at-github** [comment]
The tool that I used to make the minimal downloads is published in https://github.com/Daniel-at-github/pyvideo_scrape 

Any opinions in merging all minimal_download and publishing it as is?

**Comment by Daniel-at-github** [comment]
Uploaded a merge to [all--minimal-download](https://github.com/pyvideo/data/tree/all--minimal-download) branch as preview.

**Comment by Daniel-at-github** [comment]
Hi everyone @redapple, @logston, @willkg, @thejessleigh, @akuchling, @lgh2, @jonemo, @codersquid, @jtemporal, @lorenanicole (sorry if spammed or left out anyone),

Last months have been slow times for pyvideo. 
I'm thinking in deploying all pull request tagged as [minimal_download](https://github.com/pyvideo/data/pulls?q=is%3Apr+is%3Aopen+label%3Aminimal_download). All this pull request are far from done, but pyvideo is far behind of what it could be and, perhaps, this enables more people to contribute.

Any feedback is appreciated.

How you see it better?:
* Current workflow: Only deploy a enough finished product.
* Proposed workflow: Deploy "minimal download" skeleton (Title, video, thumbnail, date, event url; but not speaker nor description) and wait for contributions to finish it.

**Comment by akuchling** [comment]
I think you should merge the minimal versions.  That way the pyvideo database is as complete as possible.

It's probably not worth the effort to fill in complete descriptions or author info for talks from 2012/2013 -- if there's a talk that's still relevant today or an author wants a complete listing for their own talks, they can fill a pull request.  Then we can focus on getting complete data for recent conferences.

**Comment by willkg** [comment]
In my day, we switched to a minimal model. We either had an automatically generated quality report or were in the process of writing scaffolding for one so we knew which videos needed work. That was all fine. Stubs are good. I think it was rare for those videos to get fleshed out after the initial import. @codersquid might remember better since she guided most of that work.

I do know that contributors don't magically show up and I don't think speakers fixed their videos very often. If you decide to go with a stub model with the hope that eventually the metadata for these videos will get filled out by someone somewhere, you're probably going to have to do work to make that happen. Someone should be organizing sprints and actively soliciting people to contribute during those sprints. You're also going to need to know which videos need work done, too.

I think that's everything I can think of. Past is not prologue! Hope that helps!

**Comment by redapple** [comment]
Thank you @Daniel-at-github for pushing this!

I like the "publish minimal version then improve" workflow and I also agree we should merge the current "minimal" PRs.
Publishing to PyVideo.org is quite simple now, just a PR away, and with several people able to do it. I'd rather iterate on the "production" version than spend too much time on getting a perfect new conf dataset before publishing.

I agree with @willkg that it is and always will be difficult to get fixes from speakers themselves. Many do not know about PyVideo, those who know probably do no follow any feed telling them the conference they spoke at has published videos or for that matter that PyVideo has them for review. (and if we wanted to notify someone, we'd have to somehow know the speakers --which is hard with minimal information from the talk video--, get their GitHub nick and/or social media nick to ask them directly).

I also like @willkg hint at an (automated) process to check the quality of the metadata and maybe suggest corrections. E.g
- conference name is in title --> can be removed
- part of title looks like a person's name --> put it in `"speakers"` (libraries like https://github.com/datamade/probablepeople could help here)
- date range for a conference is more than 1 week, or year of talk is not the same as year of conference
- tags could be suggested using topic modeling
...
pyvideo/data is great material to play with NLP tools and there are plenty in the Python world. I'm sure there's tons of things we could automate and correct, for examaple with a bot submitting PR that a human could validate and merge or dismiss once in a while.

**Comment by redapple** [comment]
I guess we can close this one. Thank you @Daniel-at-github for this!
