### ISSUE TITLE
DjangoCon Europe 2016 links are broken

### ISSUE THREAD

**Issue by jonemo** [pyvideo/data#584]
Something seems to be wrong with DjangoCon Europe 2016. Search results for videos from the event don't contain a video snapshot and link to a 404 error page (for an example, search `reactjs`). The event page contains placeholder snapshot images: https://pyvideo.org/events/djangocon-europe-2016.html And the talk pages linked from the events page don't contain a video.

**Comment by redapple** [comment]
I haven't the search result links but all the wistia.com video links in the talks metadata are dead, e.g. https://fast.wistia.com/embed/iframe/h643dwrafs

**Comment by redapple** [comment]
Maybe it's related to this change: https://github.com/pyvideo/data/pull/346
I have never looked at how links are built or how the search results are built, but somehow, they are definitely not in sync.

**Comment by redapple** [comment]
I believe this one is for @zerok or @ulope

**Comment by zerok** [comment]
I’ll try to find time for it this weekend 🙂

**Comment by zerok** [comment]
Looks like opbeat switch to Vimeo. I'll update the links.

**Comment by redapple** [comment]
@zerok , I tried the links with the local webserver and indeed, the videos work when embedded

**Comment by redapple** [comment]
@zerok , @watson is looking into this

**Comment by watson** [comment]
They should all now work again. Only one is https://pyvideo.org/djangocon-europe-2016/django-and-reactjs-the-good-the-bad-and-the-ugly.html which I'm just looking into

**Comment by watson** [comment]
I think the last video uses the wrong vimeo ID, that's why it's not working. The correct one is [271032615](https://player.vimeo.com/video/271032615)

**Comment by redapple** [comment]
Thank you @watson .
I fixed the link in https://github.com/pyvideo/data/commit/f417fcd02b9e85a2b03cbb0deebf77202d63c99b

**Comment by zerok** [comment]
Thank you :)

**Comment by redapple** [comment]
@zerok , there's still an issue with search currently (a different one).
I've opened https://github.com/pyvideo/pyvideo/issues/185
