### ISSUE TITLE
Update documentation in CONTRIBUTING.rst for adding data

### ISSUE THREAD

**Issue by thejessleigh** [pyvideo/data#595]
It's been a while since I contributed, and looking over the issues it looks like a lot of the work left to be done is uploading the full versions of conferences we already have minimal downloads for. I see the full video schema [here](https://github.com/pyvideo/data/blob/master/.schemas/video.json), but how much of this data do we require in order to call a video "done?"

 I'm happy to update the docs with relevant info. Just want to make sure I'm maximizing my time helping out and not creating more work for y'all 😄

**Comment by thejessleigh** [comment]
Oh, I'm just seeing #517 now - it must have gotten buried in my email. Sounds like we want as much information as possible, but that current minimal downloads definitely need speaker(s) and description populated. Is this correct? If so, I'll throw up a PR to clarify the distinction in the docs.

**Comment by Daniel-at-github** [comment]
Thanks !!
