### ISSUE TITLE
Name normalisation policy

### ISSUE THREAD

**Issue by freakboy3742** [pyvideo/data#62]
Can you clarify the preferred name normalisation policy for speakers?

For example, I'm currently listed twice:

http://pyvideo.org/speaker/dr-russell-keith-magee.html
http://pyvideo.org/speaker/russell-keith-magee.html

I went to make a change to one of the videos, and discovered 282c63e01e7f26e7ae9ef5a63d3b3ed56fa44efd. 

This would seem to suggest that normalising _in_ the "Dr" is the preferred approach; however, it means that you can't find me under "R" (or "K", or "M") where most people would expect to find me in the speaker index.

I'm happy to make the change to my entries; I just want to have the policy clarified before I work up the patch.

**Comment by zerok** [comment]
Hey :-)

I don't think we have a policy right now and the speaker-"index" is less than optimal as it is right now anyway. We basically just have one string for the whole name of a speaker. IMHO just say under what name you want to be listed and it will get done :-) (PR welcome but not necessary as I have a train-ride home tomorrow and mostly working WiFi)

We really should improve the speaker index page 🙄

**Comment by codersquid** [comment]
I think names should be according to the speaker's preference.

**Comment by akuchling** [comment]
There's no deep normalization policy.  I put in the 'Dr' out of paranoia -- some people get very mad if you leave off such honorifics in a professional context.  So if Dr. Keith-Magee doesn't mind, the 'Dr.' could certainly be removed.

I agree a better fix is to have first/last/prefix/suffix name fields.

**Comment by freakboy3742** [comment]
@akuchling I totally understand (and appreciate) the sensitivity about the Dr honorific - I know many (especially in academic circles) are very protective of it. FTR, I don't mind either way.

The bigger problem I have is that if you filter the speaker list by "R", "K" or "M", my name doesn't appear. My name and videos are listed under "D" - which isn't an obvious place to look for "Russell Keith-Magee", no matter how you butcher my name :-) A less-active speaker whose name doesn't start with D is almost impossible to find unless you know this quirk of PyVideo's ordering.

**Comment by Daniel-at-github** [comment]
@freakboy3742 I will close this as answered as:

The preferred name normalization policy for speakers:
1. What the speaker asks
1. As already is in pyvideo in previous talks (if the person that makes the PR remembers to find)
1. As is in the conference youtube/web page

We have no problem in changing it whenever you say (or pull request) that you want it changed. For the filtering problem it could be changed to something like:
* Russell Keith-Magee, Dr.
* Russell Keith-Magee (Dr.)
