### ISSUE TITLE
PyBay 2016 videos

### ISSUE THREAD

**Issue by zerok** [pyvideo/data#64]
... are available now :) 

https://www.youtube.com/playlist?list=PL85KuAjbN_gtGn4v1ELSWJlTFZF_5Ciog

**Comment by Daniel-at-github** [comment]
Slides: https://speakerdeck.com/pybay2016
Schedule:
* http://www.pybay.com/schedule-1
* http://www.pybay.com/all-talks

Not all the talks are in the list yet. I think we should wait to see if they upload the rest of it.

**Comment by zerok** [comment]
OK :) I will just look there again next weekend and start the import if everything is there by then (otherwise: another week ;) )

**Comment by zerok** [comment]
I've contacted the pybay organisers regarding the missing videos. Let's see :-)

**Comment by zerok** [comment]
Haven't heard back yet. I will simply create the JSON files for the videos that are there in the next couple of days.

**Comment by Daniel-at-github** [comment]
Seen new content there, at least:
* https://www.youtube.com/watch?v=1ByQhAM5c1I&list=PL85KuAjbN_gtGn4v1ELSWJlTFZF_5Ciog&index=32
