### ISSUE TITLE
PyData Chicago 2016

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#75]
|  |  |
| --- | --- |
| **Web** | http://pydata.org/chicago2016/ |
| **Playlist** | https://www.youtube.com/playlist?list=PLGVZCDnMOq0pMUpVnQ8h5byVzIJNZCo2S |
|  |  |

**Comment by redapple** [comment]
It looks like https://github.com/pyvideo/data/pull/111 closes this one.

**Comment by Daniel-at-github** [comment]
Tanks again.
