### ISSUE TITLE
PyCon US 2019

### ISSUE THREAD

**Issue by Daniel-at-github** [pyvideo/data#785]
~~~ yaml
- title: PyCon US 2019
  dir: pycon-us-2019
  youtube_list:
    - https://www.youtube.com/channel/UCxs2IIVXaEHHA4BtTiWZ2mQ/videos
  related_urls:
  - label: Conference schedule
    url: https://us.pycon.org/2019/schedule/talks/
  language: eng
  dates:
    begin: 2019-05-01
    end: 2019-05-09
    default: 2019-05-03
  issue: 785
  minimal_download: false
  tags:
~~~

**Comment by Daniel-at-github** [comment]
PyCon US 2019 [web](https://us.pycon.org/2019/) is based in [Symposion](https://eldarion.com/symposion/) which publishes the [schedule in json format](https://us.pycon.org/2019/schedule/conference.json) (As seen in #526).  

Video information is missing, example:
* Lambda Calculus from the Ground Up https://www.youtube.com/watch?v=pkCLMl0e_0k
* Schedule Json entry:
  ~~~ json
  {
    "name": "Lambda Calculus from the Ground Up",
    "video_url": "",
    "recording_release": true,
    "description": "These days, programming style guides are all the rage.  However, what if your style guide was so restrictive that it only gave you single-argument functions and nothing else?  No modules, no classes, no control flow, no data structures, and not even any primitives like integers or regular expressions.  Just functions.  Could you actually program anything at all?    Surprisingly, the answer is yes.   In this tutorial,  you'll learn how as you work through a ground-up derivation of the lambda calculus in Python.\r\n\r\nYou will learn nothing practically useful in this tutorial. No packaging. No tools. No libraries. No deployment. No magic Python programming techniques. And certainly learn nothing you would ever want to apply to a real project.  You will, on the other hand, have a lot of fun, be completely amazed, and learn some foundational computer science that is a jumping off point for further explorations of functional programming, type theory, programming languages, and more. \r\n\r\n",
    "conf_key": 78,
    "duration": 200,
    "authors": [
      "David Beazley"
    ],
    "conf_url": "https://us.pycon.org/2019/schedule/presentation/79/",
    "start": "2019-05-01T09:00:00",
    "end": "2019-05-01T12:20:00",
    "tags": "",
    "assets_url": "",
    "abstract": "",
    "room": "Room 9",
    "slides_url": "",
    "kind": "tutorial"
  }
  ~~~

Any one of you know how to contact pycon us web admins (maybe @lorenanicole, @ewdurbin or @thejessleigh) to fill this fields. I could volunteer (today are 16 videos in https://www.youtube.com/channel/UCxs2IIVXaEHHA4BtTiWZ2mQ/videos , seems doable day by day).
My PGP: https://keybase.io/daniel_san

**Comment by thejessleigh** [comment]
I don’t know who manages the data entry here. @ewdurbin seems like your best bet here. If you need help manually filling in gaps on a pyvideo PR I’m happy to help out on Monday or Tuesday

**Comment by Daniel-at-github** [comment]
Thanks @thejessleigh !
At the end I could automate almost all (34/37) joining [schedule data in json format](https://us.pycon.org/2019/schedule/conference.json) with data scraped with [pyvideo_scrape](https://github.com/pyvideo/pyvideo_scrape) by title.

Now, waiting for more videos.
