### ISSUE TITLE
Can we add into this repo videos from local meetups?

### ISSUE THREAD

**Issue by shurph** [pyvideo/data#911]
Hi, we have few (>100) videos from our local python meetups in Minsk, Belarus.
It will be good to hold links and meta information for these videos in some relible place. The pyvideo.org is good choice for this purpose, I think :-)

if it possible, what is the best way to organize directories for meetups?
I mean, if we have 7 years of videos maybe it will be good to have directories like minsk-python-meetup-2013, minsk-python-meetup-2014, ... and so one.

**Comment by di** [comment]
I think this would be totally fine! We have some videos from regional meetups already. Some of them are just organized into a single top-level directory (e.g. `minsk-python-meetup`) but I think it would be fine to split it by dates if you'd prefer.

**Comment by Daniel-at-github** [comment]
Hi @shurph, if you (the Minsk Python Meetup) maintain it, you can do as you prefer.

You could scrape it with [pyvideo_scrape](https://github.com/pyvideo/pyvideo_scrape) with this `event.yml` config file: 
~~~ yaml
- title: Minsk Python Meetup
  dir: minsk-python-meetup
  youtube_list:
    - https://www.youtube.com/playlist?list=PLjiAaL1HtGPaMPlrZGCDzUCTsVAyTbHJ4
    - https://www.youtube.com/playlist?list=PLjiAaL1HtGPb8U9f0QPOQXcbJaR8atAPR
    - https://www.youtube.com/playlist?list=PLjiAaL1HtGPalbm2NI4ZTyGQgisC2l9ci
    - https://www.youtube.com/playlist?list=PLjiAaL1HtGPZ_FMcput9vP32hZ48TCYMG
    - https://www.youtube.com/playlist?list=PLjiAaL1HtGPYadniXqciY8c8DUCyV-1xU
    - https://www.youtube.com/playlist?list=PLjiAaL1HtGPY3c3odkiXkFD0XuxvQc2Gf
    - https://www.youtube.com/playlist?list=PLjiAaL1HtGPboVADzNr2_WdSX3Jte5lG9
  related_urls:
  - label: Meetup page (facebook)
    url: https://www.facebook.com/MinskPythonMeetup
  language: rus
#   dates:
#     begin: 2013-01-01
#     end: 2019-12-31
#     default: 2019-12-31
  issue: 911
  minimal_download: false
  tags:
~~~

Or by year like this
~~~ yaml
- title: Minsk Python Meetup 2019
  dir: minsk-python-meetup-2019
  youtube_list:
    - https://www.youtube.com/playlist?list=PLjiAaL1HtGPaMPlrZGCDzUCTsVAyTbHJ4
  related_urls:
  # ...
~~~

Whenever a new video is published you could add it with:
~~~ yaml
  # ...
  overwrite:
    # all: true # takes precedence over add_new_files and existing_files_fields
    add_new_files: true
  # ...
~~~ 

The files produced by the scraping need some cleaning(You could use [pyvideo_lektor](https://github.com/pyvideo/pyvideo_lektor) for it):
* `speaker` is missing (as to do task the field have in it TODO).
* Clean each field to contain only what the field name says:
  * `title`: Only the title. No speaker name, no conference/meetup name, ...
  * `description`: Only the description of the talk. No speaker name, no conference/meetup name or description, ... Is the restructured test OK? 
  * `tag`: Only lower case descriptive tag that helps in searching. No speaker name, no conference/meetup name, no "python" (all videos are about python), ...
  * `related_urls`: Take a look if you want to label it more descriptive than the url
  * `language`: Is it "eng", "rus" or other language in the video? ([ISO_639-3 language codes](https://en.wikipedia.org/wiki/ISO_639-3))

Too much work? If you want to publish all the talks and polish the data later you can start with a minimal download:
~~~ yaml
  minimal_download: true
~~~ 

Hope it helps.

**Comment by shurph** [comment]
Thank you @Daniel-at-github! Will do it after holidays, in Jan.

@di , thank you, too! 

:-)
