### ISSUE TITLE
Search filtering and ordering by year

### ISSUE THREAD

**Issue by AstroMatt** [pyvideo/data#921]
PyVideo has grown. And this is super good! But with this there's a lot of old videos from 2014, 2015 with description of things which you do differently now.

Can you please add an option to filter your results by year, or at least order results by date?

The most important is date, but there are some other desirable filtering options:
- length
- conference
- speaker

**Comment by di** [comment]
I think this issue probably belongs at https://github.com/pyvideo/pyvideo instead, this repository is just to hold the data. (I'd just transfer it but I don't have permissions).

**Comment by AstroMatt** [comment]
Thank you, I have created https://github.com/pyvideo/pyvideo/issues/243
